version: '2'

services:
  db:
    image: mariadb:10.5.2
    restart: always
    env_file:
      - .env_mysql
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306"
    mem_limit: 1000m
    mem_reservation: 300m

  app:
    depends_on:
      - db
    links:
      - db:db
    image: pvrmza/docker-observium:20230321
    restart: always
    env_file:
      - .env_observium
    volumes:
      - config:/config
    ports:
      - "80:80"
    mem_limit: 1000m
    mem_reservation: 600m


volumes:
  db_data:
  config:

