version: '2'

services:
  db:
    image: mariadb:10.5.2
    restart: always
    env_file:
      - .env_mysql
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306"


  app:
    depends_on:
      - db
    links:
      - db:db
    image: docker-observium:201017
    #image: pvrmza/docker-observium
    restart: always
    env_file:
      - .env_observium
    volumes:
      - config:/config
    ports:
      - "80:80"

volumes:
  db_data:
  config:

