version: '2'

services:
  db:
    image: mariadb:10.5.2
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=9459123fdf62cc04
      - MYSQL_DATABASE=observium
      - MYSQL_USER=observium
      - MYSQL_PASSWORD=observiumpwd
      - TZ="America/Argentina/Mendoza" 
    volumes:
      - db_data:/data/db
    ports:
      - "3306"


  app:
    depends_on:
      - db
    links:
      - db:db
    image: observium:200402
    restart: always
    environment:
      - TZ="America/Argentina/Mendoza" 
      - VIRTUAL_HOST=observium.micasa.local
      - VIRTUAL_PORT=80 
      - OBSERVIUM_DB_HOST=db 
      - OBSERVIUM_DB_USER=observium 
      - OBSERVIUM_DB_PASS=observiumpwd 
      - OBSERVIUM_DB_DB=observium
      - OBSERVIUM_ADMIN_USER=admin
      - OBSERVIUM_ADMIN_PASS=admin
    volumes:
      - config:/config
    ports:
      - "80:80"

volumes:
  db_data:
  config:

